# Generated by Django 2.2.12 on 2020-05-08 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deal_reference', models.CharField(max_length=128)),
                ('currency_pair', models.CharField(max_length=8)),
                ('buy_currency', models.CharField(max_length=4)),
                ('sell_currency', models.CharField(max_length=4)),
                ('amount', models.IntegerField(default=0)),
                ('client_id', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=128)),
                ('iban_bank_account', models.CharField(max_length=24)),
                ('status', models.CharField(max_length=24)),
                ('amount', models.IntegerField(default=0)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Payment')),
            ],
        ),
    ]
